### ISSUE TITLE
change soil texture visual enhancement

### ISSUE THREAD

**Issue by Sethgno** [michelegargiulo/ZenCloche#3]
if its possible idk, but itd be cool to add an argument for specifying the block texture that gets used as the soil. regular dirt gets transformed to farmland but biomesoplenty soil would need this feature to function the same, idk how it would function with multiple soils though, maybe just override all of them

**Comment by michelegargiulo** [comment]
Implemented. Version 1.3 is uploading to CurseForge and Modrinth
